### ISSUE TITLE
Request for help - Unable to use ES256 algorithm

### ISSUE THREAD

**Issue by drupol** [facile-it/php-jose-verifier#1]
Hello,

I tried to verify a token signed with ES256 algorithm and I'm unable to do it yet.

Here's a [gist](https://gist.github.com/drupol/12458e515c446aa42240ef5be319a04f), could you please let me know what is wrong?

When I run this example, I get:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Wrong key type. in vendor/web-token/jwt-framework/src/SignatureAlgorithm/ECDSA/ECDSA.php:72
Stack trace:
#0 vendor/web-token/jwt-framework/src/SignatureAlgorithm/ECDSA/ECDSA.php(41): Jose\Component\Signature\Algorithm\ECDSA->checkKey()
#1 vendor/web-token/jwt-framework/src/Component/Signature/JWSBuilder.php(168): Jose\Component\Signature\Algorithm\ECDSA->sign()
#2 /test.php(34): Jose\Component\Signature\JWSBuilder->build()
#3 {main}
  thrown in vendor/web-token/jwt-framework/src/SignatureAlgorithm/ECDSA/ECDSA.php on line 72
```

**Comment by thomasvargiu** [comment]
Hello @drupol,

`ES256` is an elliptic curve alghorithm. Read more on `web-token/jwt-framework` framework documentation about [`JWKFactory`](https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset/key-management#elliptic-curve-key-pair).

So you should use:

```php
$jwk = JWKFactory::createECKey('P-256', ['alg' => 'ES256', 'use' => 'sig']);
```
