### ISSUE TITLE
Recommended path to implementing custom claims checkers?

### ISSUE THREAD

**Issue by cooperaj** [facile-it/php-jose-verifier#13]
I'm faced with needing to implement custom claims checking wrapped in an out of band signature/public key.

- a mandatory **vc** "Verfiable Credential" claim
- Verification that an embedded JWT has the correct **sub** value.

My first approach was to build a custom verifier using the TokenVerifierInterface and the AbstractTokenVerifier class but I've found it exceedingly hard to work around the usage of final and internal classes. To the point where I'm looking at just pulling the contents of more complex methods (create) and to essentially copy the Validate class. 

Am I missing something? How can I implement this without reimplementing a lot of JWT unpacking, signature verfication and claims checkign boilerplate?

I thought this was the best place for it but I'm using this library via my usage of php-openid-client

**Comment by thomasvargiu** [comment]
Hi. We implemented jsut the standard claim checker for JOSE specifications. If need to have more claim checker, you should add your logic when retrieving and validate the JWT.
I suggest you the use of the same library that this one use.
Please see https://web-token.spomky-labs.com/the-components/claim-checker
